import TrackList from "@/components/trackList/TrackList";
import useSpotifyClient from "@/hooks/useSpotifyClient";
import Head from "next/head";
import { useState } from "react";
import type { Track } from "spotify-api.js";

const Home = () => {
    const { spotifyClient } = useSpotifyClient();

    const [spotifyData, setSpotifyData] = useState<{ tracks?: Track[] }>({});
    const [searchKey, setSearchKey] = useState("");

    const searchTracks = async (e: any) => {
        e.preventDefault();
        try {
            const res = await spotifyClient?.search(searchKey ?? "", { types: ["track"] });
            setSpotifyData({ ...spotifyData, tracks: res?.tracks });
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col items-center p-5">
                <h2 className="text-2xl">Search artist</h2>
                <form onSubmit={searchTracks}>
                    <input type="text" onChange={(e) => setSearchKey(e.target.value)} />
                    <button className="button" type={"submit"}>
                        Search
                    </button>
                </form>
                <TrackList tracks={spotifyData.tracks ?? []} />
            </main>
        </>
    );
};

export default Home;
